### PR TITLE
Shorter crop options, slightly better About text

### PR DESCRIPTION
**Pull request by humdingerb**
* As it's all under "Cropping options", shorten "Top crop size" etc. to simply "Top".
* Slightly improved wording of the thanks in the About window.
* Updated en.catkeys

### CODE REVIEW

**Comment by humdingerb** [comment]
The thanks in the About window are a bit weird. Cull 'em?

**Comment by andimachovec** [comment]
> The thanks in the About window are a bit weird. Cull 'em?

I agree that they are weird. I just copied them from the original about tab when I added the about box. As for whether to remove them: Maybe ask the original author (Zach Dykstra) before doing so, he´s online in the IRC channel quite regularly.

**Comment by humdingerb** [comment]
I haven't been too often on IRC lately...
Let's see if we can summon Zach: /me waves furiously in @zdykstra 's general direction.
@zdykstra: What are your thoughts on the "Thanks" part of the AboutWindow: Remove or streamline it a bit?

**Comment by zdykstra** [comment]
If it were up to me, I'd leave it. The `Thanks` window is a product of it's time - a little learning project created at night while I talked on IRC with friends. With that said, I've handed over all rights/responsibilities to this group - so you're free to change anything as you see fit!

**Comment by humdingerb** [comment]
Thanks for the quick reply. Let's keep as is then. After all, it's text in the AboutWindow, not some vital part of the app. :)

**Pull request merged**
