### PR TITLE
add RDEF file and native about dialog

### PR DESCRIPTION
**Pull request by andimachovec**
Added a menu bar with an "About" option which displays a standard about dialog. The version info is fetched from the rdef file. Having the app signature in the RDEF also make the app discoverable by QuickLaunch

### CODE REVIEW

**Comment by andimachovec** [comment]
fixes #30 
At least the main part of it. Fetching the version number of the installed ffmpeg will have to wait a little bit, I have to make some changes to the class that launches the ffmpeg binary first

**Comment by andimachovec** [comment]
@scottmc :  Could you take a look at this PR please, if you have the time ;-)

**Comment by scottmc** [comment]
I get a warning in ffpui-application.cpp:28:69: ISO C++ forbids converting a string constant to 'char*'
Otherwise, seems to work as expected.

**Comment by andimachovec** [comment]
That compiler warning was always there from before I first touched the code. It´s fixed now ;-)

**Pull request merged**
