### PR TITLE
Job Manager Progress

### PR DESCRIPTION
**Pull request by humdingerb**
Tried to keep smaller separate commits.
All revolve around the job manager, but [Extract current encoding time in CommandLauncher](https://github.com/HaikuArchives/ffmpegGUI/commit/ef03074a90a90ed84a7d402a48942dd9789fd6c7) maybe worth a look (hello @andimachovec :) ), as it moves the time-string to seconds-int32 into the commandlauncher. Than minorly affects the progress display for normal encodings.

### CODE REVIEW

**Comment by andimachovec** [comment]
Moving the elapsed time parsing into CommandLauncher is a good idea in my view. Implementation looks good as well, and it was working during my tests. What more do we want? :-) 
Job Manager works nicely, the only thing that confused me a bit is viewing the logs. The "Show Log" button in the job manager window was always disabled when I ran some test jobs. Is this a bug or does the button only get enabled when errors occur?

**Comment by humdingerb** [comment]
Thanks for the quick review. And it being positive. :)

Yes, since the log is only of interest in case of error - otherwise it's just a row of progress output - I thought that should do. You think renaming the button to "Error log" would be a good hint?

**Comment by andimachovec** [comment]
> Thanks for the quick review. And it being positive. :)
I would have loved to tear your code apart in my review but didn't find anything that gave me a reason to do so ;-)


> Yes, since the log is only of interest in case of error - otherwise it's just a row of progress output - I thought that should do. You think renaming the button to "Error log" would be a good hint?

Yeah, I agree with that. "Error log" would probably be the better description.

**Comment by humdingerb** [comment]
Thanks! PR updated.
I'll merge then as I have some more minor polishings a want to work on.

**Pull request merged**
