### PR TITLE
Formatlayout

### PR DESCRIPTION
**Pull request by humdingerb**

### CODE REVIEW

**Comment by andimachovec** [comment]
> Oops... I'll see if I can squash your already merged commits in there when merging...

This looks a bit messy, how did my commits end up in this pull request? I'm not enough of a github and git expert to exactly know what to do here but I'd cancel the pull request, rebase the formatlayout branch with master, resolve the conflicts, and then make new PR.

**Comment by humdingerb** [comment]
There are still only my changes in there. It should be just a matter of squashing those 3 commits and editing the commit message.

**Comment by andimachovec** [comment]
Ok, great. That's much easier :-)

**Comment by humdingerb** [comment]
I take that as a vote to merge. :)

**Comment by andimachovec** [comment]
> I take that as a vote to merge. :)

Ohh noo!!! Just kidding, yes it is ;-)

**Pull request merged**
