### PR TITLE
Convert GUI from liblayout to native Haiku layout API

### PR DESCRIPTION
**Pull request by andimachovec**
I tried to stay as close as possible to the liblayout version although I don't neccessarily agree with all design decisions. Exceptions are the boxes that fill out whole tabs like in the output and about tabs.

### CODE REVIEW

**Comment by andimachovec** [comment]
fixes #15

**Comment by diversys** [comment]
Very nice! There is another app waiting for the same treatment ;) https://github.com/HaikuArchives/Beam/issues/1

**Comment by andimachovec** [comment]
> Very nice! There is another app waiting for the same treatment ;) [HaikuArchives/Beam#1](https://github.com/HaikuArchives/Beam/issues/1)

Thanks, I'll take a look at it ;-)

**Comment by scottmc** [comment]
I get fatal error missing MApplication.h when running make.  Perhaps I'm missing one or more required libs?  Also it's showing liblayout in the makefile still on the SYSTEM_INCLUDE_PATHS

**Comment by diversys** [comment]
I had the same thing until I realised I forgot to switch branch with `git checkout layout_api`.

**Comment by andimachovec** [comment]
> I get fatal error missing MApplication.h when running make. Perhaps I'm missing one or more required libs? Also it's showing liblayout in the makefile still on the SYSTEM_INCLUDE_PATHS

> I had the same thing until I realised I forgot to switch branch with `git checkout layout_api`.

Sorry about that guys. I always do my PRs from a dedicated branch, not from master. Should have mentioned it in the comments.

**Comment by andimachovec** [comment]
Thanks for merging @scottmc

**Pull request merged**
