### PR TITLE
Show media info gained from ffprobe

### PR DESCRIPTION
**Pull request by humdingerb**
This is a WIP... there are issues.

### CODE REVIEW

**Comment by humdingerb** [comment]
I thought, I re-use CommandLauncher to execute the ffprobe command.
It appears to almost work, CommandLauncher receives the M_INFO_COMMAND message and executes the ffprobe line. I see the ffprobe output when started from Terminal:
```
codec_name=h264
width=1440
height=1080
r_frame_rate=30/1
duration=7.300000
bit_rate=4686963
codec_name=aac
sample_rate=48000
channel_layout=stereo
bit_rate=129974
```
But the "buffer" is always empty - shown when I ouput the buffer to syslog.

My main problem is that I don't quite understand how the output from the ffprobe thread makes it back to CommandLauncher - and why it's empty...
I also suspect that - once that works - I won't get the lines one at a time, but all output lines in one buffer. That wouldn't be a problem, I would just have to adjust how I put it into my variables.

@andimachovec  : "HELP!"  :)

**Comment by andimachovec** [comment]
> I thought, I re-use CommandLauncher to execute the ffprobe command.

Yes, that´s what I had planned on doing since the idea about showing media info came up. It should be possible without too much change, however, at the moment CommandLauncher is very specifically implemented to run video encoding with ffmpeg. A few things need to be changed for more general use. 
We can work on this together, but it will have to wait until next year ;-) Probably a few days into 2023 ;-)

Ich wünsch dir einen guten Rutsch ins neue Jahr!
Liebe Grüsse, 
Andi

**Comment by humdingerb** [comment]
Alright, let's have another (sober again) look next year. :)
Experiment with the code of this PR, when you feel like it.
Gutes Neues!  \o/

**Comment by humdingerb** [comment]
Hi @andimachovec 
I played around a bit more. Appears like ffmpeg does its output on stderr and ffprobe on stdout.
I have massaged the CommandLauncher to account for that. Please have a look if it seems OK. We (or rather you, I suppose) can simplify and beautify things later.

It works most of the time. Until it hiccups onthe audio track for some files. :(
Normally, it should output 6 "info=pair" per stream, the video track first, then audio. An audio- or video-only file should therefore have 6 "info=pairs", audio+video 12.
I have a "count" printf that shows sometimes other numbers. It also seems to get triggered more than once... Isn't it guaranteed that the ffprobe output is complete when its BMessage is sent?

Anyway, I'd appreciate if you had a look.
Thanks!

**Comment by andimachovec** [comment]
Hi @humdingerb ! Seems you had a good run doing some coding over the last days. I´ll check it out tomorrow and let you know if I find something.

**Comment by humdingerb** [comment]
Thanks @andimachovec!
I the night I had a brain wave: I don't rely on the number of output lines to determine if we have a audio- or video-only file, but simply check if my list includes a string "width" (==video) or "sample_rate (==audio).
The ouput from the commanlauncher does appear to be always complete, even though my CountLines() for some reason returns different numbers. I kept that "count"printf in the code for now, in case you want to investigate.

I still value your opinion/criticism of the code in this PR. If nothing is fundamentally bad, I suggest to merge it soon and you/I can improve it in another PR.
Meanwhile, I'll tweak some numbers, like the format for bitrate, samplerate, duration etc.

**Comment by andimachovec** [comment]
> I still value your opinion/criticism of the code in this PR.

Looks very good in general, you´ve been quite busy over the last week :-) . It´s good that you don´t rely on the number of lines, I´d probably do the string parsing a bit differently still. (no splitting in lines, just checking for the existence/position of certain string marks and the making my way to the desired values). You can see an example in the parsing code for the progress information in the case for M_PROGRESS in ffguiwin::MessageReceived(). But that doesn´t mean you have to change your parsing code. I´ll take a closer look and see if I can spot an error.

**Comment by andimachovec** [comment]
After seeing the output format of ffprobe I´d stick with the list approach. Let me see if I can simplify and maybe improve it a little bit.

**Comment by humdingerb** [comment]
Yes, please! :)

What I don't quite understand, is why the one-time call of the ffprobe command results in sometimes several messages sent to the main window (as evidenced by more than one "data:" or "count:" printf()s). This seems to mess things up sometimes, esp, for files with more or less than one video and one audio stream, or an additional subtitle stream.
If we could ensure that we got only one BMessage with the whole output, we could add "index" to the "stream=" parameter of the ffprobe command. Then we would know that "index=0" is the video stream, "index=1" is the first audio (and for the time being forget the rest).
If you don't find the magic bullet, we could consider sending two ffprobe commands, one for stream v:0, one for stream a:0. But I foresee major messup trying to capture two outputs...
Maybe pipe into a temp file instead, if that removes the output chaos?

**Comment by humdingerb** [comment]
BTW, as hacky as it it seems, writing to a file and "cat"ing it in the end does appear to guarantee to end up with one BMessage with the complete output.

Something like this (it strings two ffprobe commands together, one for 1st video, one for 1st audio track; doesn't fit the rest of the code, just as experiment if the line "count" is constant. It is.):

```
	BString command;
	command << "ffprobe -v error -show_entries stream=index,codec_type,codec_name,width,height,bit_rate,"
		"r_frame_rate,duration,sample_rate,channel_layout -of default=noprint_wrappers=1 "
		"-select_streams v:0 "
		<< "\"" << sourcefile->Text() << "\" > /tmp/probe.txt ; ";
	command << "ffprobe -v error -show_entries stream=index,codec_type,codec_name,bit_rate,"
		"duration,sample_rate,channel_layout -of default=noprint_wrappers=1 "
		"-select_streams a:0 "
		<< "\"" << sourcefile->Text() << "\" >> /tmp/probe.txt ; cat /tmp/probe.txt";
```

**Comment by humdingerb** [comment]
@andimachovec , I just updated the PR. I just didn't find no peace until I solved it. I hope you didn't invest much time yet in looking over the old code.

It does work now, even without the strange hack of piping to a temp file.

I think the code is nicer now, too. I find the strings now by keyname which makes it more robust in case ffprobe changes output order. I do have trick it a bit, by removing the "codec_name" and "bit_rate", because both video and audio streams use the same keyname and BStringList::IndexOf() would be confused.

Does it look OK to you? If so, I'll remove the debug printf() and we're done here.

**Comment by andimachovec** [comment]
> I hope you didn't invest much time yet in looking over the old code.

Don´t worry, I didn´t have the time to look further into it yesterday. 

> It does work now, even without the strange hack of piping to a temp file.

I have to say I really dislike using temporary files unless absolutely necessary. 

> Does it look OK to you? If so, I'll remove the debug printf() and we're done here.

If you want me to really take  a close look at the code before merging I´m gonna need a few days until I find the time. If it works you can of course merge it anyway and we can improve it later.

**Comment by humdingerb** [comment]
> I have to say I really dislike using temporary files unless absolutely necessary.

Me too, therefore I'm happy that it works without that. I think you misread that...
Having to call external apps and parse their output is bad enough... :)

I think we should wait with the merge until you can give it a spin. Maybe over the weekend.
I tested with a bunch of files, and it appears to work fine.

**Comment by humdingerb** [comment]
I may have to point out that I'm a dummy...

The reason why I got several incomplete BMessages mixed with weird contents sometimes was because of the debug printf()s! Those printf()s printed into the same stdout that our commandthread is capturing...

I feel a bit more stupid than usual now. :}
I'll remove the debug stuff and update the PR.

**Comment by humdingerb** [comment]
Oops. I had to update the PR, just seen that I had everywhere, e.g.

`if (fVideoFramerate != "" || fVideoFramerate != "N/A")`

instead of 

`if (fVideoFramerate != "" && fVideoFramerate != "N/A")`

@andimachovec : Maybe post a quick comment here when you start looking at the code, so I don't make any updates while you're at it...

**Comment by humdingerb** [comment]
@andimachovec , Sorry, I'm reallyspamming this PR.

**Note:** While I still don't understand the mechanics of the stdout capturing, I experimentally moved "char buffer[4096]" outside while-loop.

Though with better results, there are still several BMessages with the stdout buffer sent. I ammended the PR to print to syslog. If you watch with "tail -f /var/log/syslog" you see on a source file drop, for example:

```
USER: buffer 1:
USER: 
USER: buffer 2:
USER: codec_name=h264
USER: width=1280
USER: height=720
USER: r_frame_rate=30/1
USER: it_rate=64401
USER: duration=1070.400000
USER: 
USER: 284011
USER: 5
USER: 0
USER: channel_layout=stereo
USER: bit_rate=83376
USER: duration=467.690889
USER: 
USER: sent!
USER: 
USER: buffer 1:
USER: codec_name=h264
USER: width=1280
USER: height=720
USER: r_frame_rate=30/1
USER: it_rate=64401
USER: duration=1070.400000
USER: 
USER: 284011
USER: 5
USER: 0
USER: channel_layout=stereo
USER: bit_rate=83376
USER: duration=467.690889
USER: 
USER: buffer 2:
USER: duration=483.567000
USER: bit_rate=1691888
USER: 
USER: r_frame_rate=30/1
USER: it_rate=64401
USER: duration=1070.400000
USER: 
USER: 284011
USER: 5
USER: 0
USER: channel_layout=stereo
USER: bit_rate=83376
USER: duration=467.690889
USER: 
USER: sent!
USER: 
USER: buffer 1:
USER: duration=483.567000
USER: bit_rate=1691888
USER: 
USER: r_frame_rate=30/1
USER: it_rate=64401
USER: duration=1070.400000
USER: 
USER: 284011
USER: 5
USER: 0
USER: channel_layout=stereo
USER: bit_rate=83376
USER: duration=467.690889
USER: 
USER: buffer 2:
USER: codec_name=aac
USER: sample_rate=44100
USER: channel_layout=stereo
USER: bit_rate=128293
USER: duration=483.567000
USER: 
USER: 284011
USER: 5
USER: 0
USER: channel_layout=stereo
USER: bit_rate=83376
USER: duration=467.690889
USER: 
USER: sent!
USER: 
USER: buffer 1:
USER: codec_name=aac
USER: sample_rate=44100
USER: channel_layout=stereo
USER: bit_rate=128293
USER: duration=483.567000
USER: 
USER: 284011
USER: 5
USER: 0
USER: channel_layout=stereo
USER: bit_rate=83376
USER: duration=467.690889
USER: 
USER: buffer 1:
USER: 
USER: buffer 2:
USER: codec_name=h264
USER: width=1280
USER: height=720
USER: r_frame_rate=30/1
USER: duration=483.567000
USER: bit_rate=1691888
USER: 84011
USER: 5
USER: 0
USER: channel_layout=stereo
USER: bit_rate=83376
USER: duration=467.690889
USER: 
USER: sent!
USER: 
USER: buffer 1:
USER: codec_name=h264
USER: width=1280
USER: height=720
USER: r_frame_rate=30/1
USER: duration=483.567000
USER: bit_rate=1691888
USER: 84011
USER: 5
USER: 0
USER: channel_layout=stereo
USER: bit_rate=83376
USER: duration=467.690889
USER: 
USER: buffer 2:
USER: codec_name=aac
USER: sample_rate=44100
USER: channel_layout=stereo
USER: bit_rate=128293
USER: duration=483.567000
USER: 8
USER: 84011
USER: 5
USER: 0
USER: channel_layout=stereo
USER: bit_rate=83376
USER: duration=467.690889
USER: 
USER: sent!
USER: 
USER: buffer 1:
USER: codec_name=aac
USER: sample_rate=44100
USER: channel_layout=stereo
USER: bit_rate=128293
USER: duration=483.567000
USER: 8
USER: 84011
USER: 5
USER: 0
USER: channel_layout=stereo
USER: bit_rate=83376
USER: duration=467.690889
USER: 
```
That's quite excessive...
Parts of previous values appear to be repeated randomly. When unlucky, those are mixed into a "keyword=value" pair and mess up the displayed string. Most often it's the video bitrate showing "0 Kbits/s".
When you watch the mediainfo string in the GUI, you see that it gets sometimes updated when another BMessage from the commandlauncher hits.

So, if possible, we somehow need regular BMessages when reading stderr from the ffmpeg command to update the progress, and one clean BMessage from the stdout of the ffprobe commands.

**Comment by humdingerb** [comment]
I fixed the random numbers appearing by adding a "buffer[amount_read] = 0;" to null-terminate the buffer before sending it. I still see a videobitrate  of "0" sometimes...
I'll shut up now, for real... :)

**Comment by andimachovec** [comment]
Hi @humdingerb ! Here I am again, trying my best to follow up ;-) Did a bit of testing today, with results that are still somewhat confusing to me. I checked if there is anything not properly reset (buffer, BMessage content) in CommandLauncher but that all looks good. I'm starting to suspect that the 2 ffprobe commands that are sent to CommandLauncher at once are the problem. But no hard evidence as for now.  More testing tomorrow...

One thing that I'd change in the implementation of the info message parsing in ffguiwin::MessageReceived() would be to only read the message data in the case for M_INFO_OUTPUT and append it to a BString class member. And do the whole parsing when the M_INFO_FINISHED message is received. Might make things a little easier to debug.

**Comment by humdingerb** [comment]
That was very good advice! Thanks very much!
I did so in the last commit (I'll squash those into one in the end, but figured it's easier for you to see the changes).
From my tests with a dozen different clips, that seems to have fixed it all !! Give it a spin.

Only curiosity: I left two debug printf()s in and the "GUI" one at the end that shows the assembled string that appears in the GUI always lacks the "Duration" part. It's the GUI alright, so it doesn't matter. Still... hmmm....

**Comment by andimachovec** [comment]
> That was very good advice! Thanks very much!

You're welcome, I'm glad I could help. 

> From my tests with a dozen different clips, that seems to have fixed it all !! Give it a spin.

Looks very good. Did some quite extensive testing, also with dummy video files that don't contain any video or audio at all :-) No problems found so far. Seems we're getting ready to merge soon. Great job @humdingerb , I don't wanna hear you putting down your coding skills from now on ;-)
Maybe you can comment out (or remove?) the debug output statements before merging. Commenting out is sufficient for me. 

> Only curiosity: I left two debug printf()s in and the "GUI" one at the end that shows the assembled string that appears in the GUI always lacks the "Duration" part. In the GUI it's alright, so it doesn't matter. Still... hmmm....

That's an interesting one. Did some tests and found out that the "special" unicode characters (TV screen, speaker and clock symbols) seem to mess up terminal output (also tried with std::cout instead of printf(), same result). If you temporarily remove thes e characters from being added to the text BString the duration gets printed normally. 
fDuration is alway populated correctly, so the values get displayed in the GUI. BString seems to handle the unicode characters correctly. Either the problem occurs in the BString::String() method or like I said somewhere below in the terminal output code.

**Comment by andimachovec** [comment]
> It was just surprising that it (accidentally, probably) only seemed to affect the duration output. Anyway...

Maybe it was just the clock symbol character. I didn't test them individually, just removed them all, then the duration was printed out. Since it only affected the debug output I didn't investigate it further. 

> Have you any immediate plans for ffmpegGUI? Otherwise I'd make some code style changes, as it's a bit mixed now...

I've got a branch where I implemented the codec copy options for audio and video. Should be ready to submit as PR in the next few days. Would be great if you could wait with the very much needed coding style cleanup until then. Makes it a lot easier to rebase my branch with current master.

**Comment by humdingerb** [comment]
Will do.

**Pull request merged**
