### PR TITLE
Use Notifications, add checkbox "Play when finished"

### PR DESCRIPTION
**Pull request by humdingerb**

### CODE REVIEW

**Comment by humdingerb** [comment]
Since I was stuck in crimbo limbo today...
@andimachovec, tell me this is OK for you. I didn't want to bud into your project, but was bored and figured this was in my grasp to implement...
Merry Xmas! :)

**Comment by andimachovec** [comment]
Merry Christmas @humdingerb ! First of all let me make clear this is not my project, it's a collaborative thing by all that chose to contribute. I just happened to submit quite a few PRs lately. So, by all means if you are motivated and enjoy it then go for it ;-)

Getting back to this specific PR: I just checked out your changes, seems to work nicely. I like the notifications. I'm not so sure about the "play when finished" checkbox. It's great when you do an encoding job that takes, let's say up to a minute. You're still focused on the video task and expect the finished video to play. But what about an encoding that takes 10 minutes or more. You`re most likely doing something completely different (pun halfway intended :-) ) or are away from the computer when the video starts to play. Maybe we should put a play now button in the notification? Is that possible?

That said I've got no problem with merging this PR as it is. Just wanted to give a few thoughts.

**Comment by humdingerb** [comment]
Alright, just didn't want to step on your toes... :)

> I'm not so sure about the "play when finished" checkbox. It's great when you do an encoding job that takes, let's say up to a minute. You're still focused on the video task and expect the finished video to play. But what about an encoding that takes 10 minutes or more.

I think, if the users see that the encoding takes too long to patiently wait for it, and don't want to get interrupted when it's finished, they manually deactivate the "Play when finished" box before wandering off.

> Maybe we should put a play now button in the notification? Is that possible?

I amended this PR. Now, a click on the notification opens the clip. I also set the MIME type of the file after encoding, thinking that would get rid of the warning thrown by MediaPlayer, but it turns out that doesn't help. I think there's something wrong on MediaPlayer's side, because when you set another app (MediaConverter) the encoded file opens no problem.
In any case, setting the MIME type is a good thing in any case.

See if you see something fishy before I merge...
Thanks!

**Comment by andimachovec** [comment]
> I also set the MIME type of the file after encoding, thinking that would get rid of the warning thrown by MediaPlayer, but it turns out that doesn't help. I think there's something wrong on MediaPlayer's side, because when you set another app (MediaConverter) the encoded file opens no problem.

Yeah that's strange. I also get the error message. After that MediaPlayer plays back the file without problems. If the "play when finished" option is set and MediaPlayer gets opened via BRoster there's no error message. 
I'm still not totally convinced of the "play when finished" option, but if we can uncheck it by default I'm happy with it ;-)

**Comment by humdingerb** [comment]
I filed https://dev.haiku-os.org/ticket/18178 for the MediaPlayer/BNotification bug.

> I'm still not totally convinced of the "play when finished" option, but if we can uncheck it by default I'm happy with it ;-)

I amended the PR to start unchecked. In the future, we may want to save all settings.

Let's merge then and see if there's feedback from people using the app.

**Pull request merged**
