### PR TITLE
Resize spinners to fit the values

### LINKED ISSUE #36: Numeric input boxes clip numbers
Perhaps make them a little bit wider so they don't clip a wide 5 digit number such as 88888

### PR DESCRIPTION
**Pull request by andimachovec**
The minimum required width plus a bit of extra space is set on all the spinners on the main options tab. Fixes #36

### CODE REVIEW

**Comment by scottmc** [comment]
Nice progress.  I think you might want to set a min width and height of the window though, as it is now you can shrink the window nearly down to just the App option on the menu.
Also I noticed the About window title text and version feels attached to the top left, maybe add same amount of space and the "Written by:" line has.  Looking at other apps, I guess this goes away if/when an icon gets added to the About?

**Comment by andimachovec** [comment]
Thanks. Setting a minimum windows size sounds like a good idea. Let me add it to this PR before you merge it. 
The about window has it's own internal layout, not sure if we can do something here. But like you said, I think the alignment will be OK once we have an icon.

**Comment by andimachovec** [comment]
I've set the preferred window size on startup as the minimum window size. Could you check if this does what you wanted?

**Comment by andimachovec** [comment]
> I would go one more step, that is to set minimum height so that it captures the bottom of the bottom box with text in it.

If we do that the user could resize the window to hide the progress bar. I'd rather not allow that.

**Pull request merged**
