### PR TITLE
Dropped file / extension setting

### PR DESCRIPTION
**Pull request by humdingerb**
Two commits in one PR, because the 2nd commit should be uncontroversial. The 1st one, too, of course in my opinion. :)

### CODE REVIEW

**Comment by andimachovec** [comment]
Accepting output file drops is good, I should have added it when I added source file drop capability. What I don't agree with is that file drops anywhere on the app are set as source file. I think that's confusing and doesn't contribute to good usability. In my opinion file drops on the source file textcontrol should be used as source file and drops on the outputfile textcontrol as output file. Straight forward and no confusion ;-)  
No controversy on the 2nd commit, as expected :-)

**Comment by humdingerb** [comment]
My thinking was, that a source-drop is much more common than an output-drop. Most of the time, people would accept the output-file that gets autofilled when choosing the source.
Accepting a drop on the whole window as the sourcefile would then avoid having to aim for a small drop target for the majority of cases.
It's like having to drop a Bookmark file on the URL locator instead of anywhere in the Web+ window (once that worked... :) ).

Or viewed from the user perspective: I just launched the app, file boxes are empty. What would I expect when dropping a file? Me, I'd expect the app to work on the dropped file. If it does, I see that the Output is auto-filled. Neat. How to set the Output by dropping another file? Dropping anywhere will set the Source, that I've learned before. So it's logical to drop it where it should go: the Output text box.

Anyway... if I couldn't convince you, I'll change it as you wish.

**Comment by andimachovec** [comment]
> What would I expect when dropping a file? Me, I'd expect the app to work on the dropped file.

Up to this point I agree. But since we have to files that can be set by dropping (source and output), I find it confusing that I can drop one of them anywhere (source) and have to go for the specific drop area for the other one (output). 

> Anyway... if I couldn't convince you, I'll change it as you wish.

I don't really feel comfortable in having the last word on user interface matters. If you're convinced it is better this way, I´ d say lets merge it as it is. It can be quite easily changed back if too many users complain about it.

**Comment by humdingerb** [comment]
I reverted the whole-window-accepts-source-drops. If possible, we should try to compromise where possible. :)

It amended the PR, though, because I do find the target areas to drop a file rather small. I padded the areas with half the spacing between source and output text boxes. I find this makes aiming the drops easier.

> It can be quite easily changed back if too many users complain about it.

In my experience few users complain. Or praise, for that matter. :)

Anyhoo, gimme a thumb-up and I merge.

**Comment by andimachovec** [comment]
Sorry for the delay, looks good! The only problem I noticed was that dragging a source file automatically overwrites the output filename. Most likely comes from my code when I first implemented source file drag'n'drop. I think it should only do that when the output file textcontrol is empty. I can fix that myself of course, in a later PR :-)

**Comment by humdingerb** [comment]
> I noticed was that dragging a source file automatically overwrites the output filename. Most likely comes from my code when I first implemented source file drag'n'drop. I think it should only do that when the output file textcontrol is empty.

Not sure about that. Most of the time, when you select a new source file, you also want a different output file than the one you created with your previous encoding. It makes sense for the output file name to default to the dropped new source file name with adjusted extension.

**Comment by andimachovec** [comment]
Yep, you're right. Let's leave it that way.

**Comment by humdingerb** [comment]
Alright. Merge! 😃

**Pull request merged**
