### PR TITLE
Minor Layout tweaks

### PR DESCRIPTION
**Pull request by humdingerb**

### CODE REVIEW

**Comment by andimachovec** [comment]
@humdingerb This is great, I think we should remove the "Encode" box as well.

**Comment by humdingerb** [comment]
I've tried that just now. Here are screenshots:
old: http://0x0.st/oFzQ.png
new: http://0x0.st/oFz1.png
I suggest downloading both and flip back and forth with ShowImage.

What may be the case is that with the "Encode" label, the user's eyes are guided to the "Start" button, while without it the user's brain may throw everything into the options part.

I'm not sure, you can decide...

**Comment by andimachovec** [comment]
> I'm not sure, you can decide...

I like the new one, without the box better. 
I'm not much  of a UI designer but the way I see it a box is there to group UI elements together that belong together function-wise. In our case that makes sense for the boxes around the video, cropping, and audio options, because they have several controls. The encode box only has the text view and the encode button and it's pretty obvious that they belong together, even without the box. Does that make sense? :-)

**Comment by humdingerb** [comment]
Sure, makes sense. OTOH, the "Encode" BBox isn't really a box around controls, as it's side border has melted into the window border. It functions as a header for that part of the window.
Is the Start button + command line still drawing enough attention not to be overlooked?
If you say, "Yes", we'll do away with the BBox. :)

**Comment by andimachovec** [comment]
Yes ;-)

**Comment by humdingerb** [comment]
So be it. 😃

**Pull request merged**
