### PR TITLE
Add vector icon data to ffmpeg.rdef

### PR DESCRIPTION
**Pull request by Handmaus**
Here's the icon, it's basically the last version posted in the forums with very slight optimizations.

### CODE REVIEW

**Comment by humdingerb** [comment]
Thanks!
Would you mind adding the Icon-O-Matic file as well? Makes future editing easier.

**Comment by Handmaus** [comment]
You're welcome :), here's the IOM file as well.

**Comment by humdingerb** [comment]
Nice icon, thank you!

**Comment by andimachovec** [comment]
Thanks a lot for the icon, @Handmaus !

**Pull request merged**
